import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { fontSans } from "@/configs/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fontSans.className}>
      <body>{children}</body>
    </html>
  );
}
