import '@/styles/globals.css';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { fontSans } from '@/configs/fonts';
import { ThemeProvider } from '@/providers/theme';
import { ServerThemeProvider } from '@wits/next-themes';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ServerThemeProvider>
      <html lang="en" className={fontSans.className}>
        <head />
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Theme>{children}</Theme>
          </ThemeProvider>
        </body>
      </html>
    </ServerThemeProvider>
  );
}
